---
title: "homework_6"
author: "Peter"
date: "`r Sys.Date()`"
output: html_document
---




Sec 6.8 Exercises # 3,5 (use p=0.3),7,8,9,10,12,14,18 (I will discuss how to obtain credit) \

### Problem 3 \

a.


$n = 4$ rolls. 

$p_1 = \frac{1}{6}$, prob of rolling a 1. \
$p_2 = \frac{1}{6}$, prob of rolling a 2.  \
$P_{\text{else}} = \frac{4}{6}$

Using the general multinomial pmf formula we get: \

$$P(O=o, T=t) = \frac{4!}{o! \cdot t! \cdot (4-0-t)!} \cdot \frac{1}{6}^o \cdot \frac{1}{6}^t \cdot \frac{4}{6}^{4-o-t}$$ with $o \geq 0, t \geq 0, o + t \leq 0$


b.

$P(O = T)$?

We could either have $o=t=0, o=t=1, o=t=2$ since $o + t \leq 0$. \

So, we can use the formula above to solve for each case. \

$o=t=0$:

$P(0,0) = \frac{4!}{4!} \cdot \frac{1}{6}^0 \cdot \frac{1}{6}^0 \cdot \frac{4}{6}^{4} = \frac{256}{1296}$ 

$o=t=1$:

$P(1,1) = \frac{4!}{1!1!2!} \cdot \frac{1}{6}^1 \cdot \frac{1}{6}^1 \cdot \frac{4}{6}^{2} = \frac{192}{1296}$ 

$o=t=2$:

$P(2,2) = \frac{4!}{2!2!} \cdot \frac{1}{6}^2 \cdot \frac{1}{6}^2 \cdot \frac{4}{6}^{0} = \frac{6}{1296}$ 

$P(O=T) = \frac{454}{1296} = 0.3503086$


c.

$P(T=t | O = 1)$?

Using the binomial distribution pmf: \

$$P(O=1) = \binom{4}{1} \cdot \frac{1}{6}^1 \cdot \frac{5}{6}^3 = \frac{500}{1296}$$

Next we use the formula from part a: \

$$P(O=1, T=t) = \frac{4!}{1!t!(3-t)!} \cdot \frac{1}{6}^1 \cdot \frac{1}{6}^t \cdot \frac{4}{6}^{3-t}$$

So, we get: \

$$P(T=t | O = 1) = \frac{P(O=1, T=t)}{P(O=1)} = \frac{\frac{4!}{1!t!(3-t)!} \cdot \frac{1}{6}^1 \cdot \frac{1}{6}^t \cdot \frac{4}{6}^{3-t}}{\binom{4}{1} \cdot \frac{1}{6}^1 \cdot \frac{5}{6}^3}$$
This simplifies to: \

$$P(T=t | O = 1) = \binom{3}{t} \cdot \frac{1}{5}^t \cdot \frac{4}{5}^{3-t}$$ for $t \in {0, 1, 2, 3}$. 

This makes a lot of sense, we know O=1, so in the 3 remaining rolls we only care about prob of a 2, which is 1/5 chance among non 1s and others have 4/5 chance. \


d.

$P(T>0 | O = 1)$?

$P(T>0 | O = 1) = 1 - P(T = 0 | O = 1) = 1 - \binom{3}{0} \cdot \frac{1}{5}^0 \cdot \frac{4}{5}^{3} = 1 - \frac{64}{125} = \frac{61}{125} = 0.488$


### Problem 5
 
N = # of opportunities \

X = # of hits \

$X \sim Bin(p=0.3, N)$

a.

$P(N=n, X=x)$?

$P(N=n) = \frac{1}{3}$

$P(X=x | N=n) = \binom{n}{x} \cdot 0.3^x \cdot 0.7^{n-x}$.

$$P(N=n, X=x) = P(N=n) \cdot P(X=x | N=n) = \frac{1}{3} \cdot \binom{n}{x} \cdot 0.3^x \cdot 0.7^{n-x}$$.

b.

$P_X(x)$?

$$P_X(x) = \sum_{n=max(4,x)}^{6} (\frac{1}{3} \cdot \binom{n}{x} \cdot 0.3^x \cdot 0.7^{n-x})$$
$$
P_X(x) = \begin{cases} 
\frac{1}{3} \left[ \binom{4}{0}0.3^0 0.7^4 + \binom{5}{0}0.3^0 0.7^5 + \binom{6}{0}0.3^0 0.7^6 \right] = 0.17527 & \text{for } x = 0 \\
\frac{1}{3} \left[ \binom{4}{1}0.3^1 0.7^3 + \binom{5}{1}0.3^1 0.7^4 + \binom{6}{1}0.3^1 0.7^5 \right] = 0.35809 & \text{for } x = 1 \\
\frac{1}{3} \left[ \binom{4}{2}0.3^2 0.7^2 + \binom{5}{2}0.3^2 0.7^3 + \binom{6}{2}0.3^2 0.7^4 \right] = 0.29914 & \text{for } x = 2 \\
\frac{1}{3} \left[ \binom{4}{3}0.3^3 0.7^1 + \binom{5}{3}0.3^3 0.7^2 + \binom{6}{3}0.3^3 0.7^3 \right] = 0.13104 & \text{for } x = 3 \\
\frac{1}{3} \left[ \binom{4}{4}0.3^4 0.7^0 + \binom{5}{4}0.3^4 0.7^1 + \binom{6}{4}0.3^4 0.7^2 \right] = 0.03199 & \text{for } x = 4 \\
\frac{1}{3} \left[ \binom{5}{5}0.3^5 0.7^0 + \binom{6}{5}0.3^5 0.7^1 \right] = 0.00421 & \text{for } x = 5 \\
\frac{1}{3} \left[ \binom{6}{6}0.3^6 0.7^0 \right] = 0.00024 & \text{for } x = 6 \\
0 & \text{else}
\end{cases}
$$

c.

$P(N=n | X=2) = \frac{P(N=n, X=2)}{P(X=2)}$

Using $P(X=2)$ from above: \ 

$$
P(N=n \mid X=2) = \begin{cases} 
\frac{\frac{1}{3} \binom{4}{2} (0.3)^2 (0.7)^2}{0.29914} = 0.2948 & \text{if } n = 4 \\
\frac{\frac{1}{3} \binom{5}{2} (0.3)^2 (0.7)^3}{0.29914} = 0.3440 & \text{if } n = 5 \\
\frac{\frac{1}{3} \binom{6}{2} (0.3)^2 (0.7)^4}{0.29914} = 0.3612 & \text{if } n = 6 \\
0 & \text{else}
\end{cases}
$$

d.

$P(N=5 \mid X=3)$?

Using P(X=3) from above: \ 

$$P(N=5 \mid X=3) = \frac{P(N=5, X=3)}{P(X=3)} = \frac{\frac{1}{3} \binom{5}{3} (0.3)^3 (0.7)^2}{0.13104} = \frac{0.0441}{0.13104} = 0.3365$$


### Problem 7

$f(x,y) = ky, 0 < x < 2, 0 < y < 2$

a.

$1 = \int_{0}^{2} \int_{0}^{2} ky \, dx \, dy = \int_{0}^{2} 2ky \, dy = 4k$.

$k = \frac{1}{4}$.


b.

$f_X(x) = \int_{0}^{2} \frac{y}{4} \, dy = \frac{1}{2}, \quad 0 < x < 2$


c.

$$P(Y > X) = \int_{0}^{2} \int_{x}^{2} \frac{y}{4} \, dy \, dx = \int_{0}^{2} \frac{1}{2} - \frac{x^2}{8} \, dx = 1 - \frac{8}{24} = \frac{2}{3}$$


d.

$$f_{Y \mid X}(y \mid x) = \frac{f(x,y)}{f_X(x)} = \frac{\frac{4}{y}}{\frac{1}{2}} = \frac{y}{2}, \quad 0<y<2$$.


### Problem 8





### Problem 9



### Problem 10



### Problem 12



### Problem 14



### Problem 18



