---
title: "homework_3"
author: "Peter"
date: '`r Sys.Date()`'
output: html_document
---



Sec 3.8 Exercises # 5, 6, 8, 12, 14, 17, 18, 23, 28, 30, Optional Extra Credit King's Gold and Silver Chest Problem

** for problems 5 and 8, find the requested probabilities using the classical view of probability in addition to the frequency view


### Problem 5

Classical

a.

There are $\binom{9}{3}$ total ways of choosing 3 balls. \

$P(F_1) = \frac{\binom{4}{1} \cdot \binom{5}{2}}{\binom{9}{3}} = 0.476$

$P(B_1) = \frac{\binom{3}{1} \cdot \binom{6}{2}}{\binom{9}{3}} = 0.536$

b.

$P(F_1 | B_1) = \frac{\binom{4}{1} \cdot \binom{3}{1} \cdot \binom{2}{1} / \binom{9}{3}}{\binom{3}{1} \cdot \binom{6}{2} / \binom{9}{3}} = 0.533$

c.

$P(B_1 | F_1) = \frac{\binom{4}{1} \cdot \binom{3}{1} \cdot \binom{2}{1} / \binom{9}{3}}{\binom{4}{1} \cdot \binom{5}{2} / \binom{9}{3}} = 0.6$

d.

If $F_1$ and $B_1$ are independent, then $P(B_1) \cdot P(F_1) = P(B_1 \cap F_1)$.

But, $.476 \cdot .536 = 0.255136 \neq P(B_1 \cap F_1) = 0.286$.



Frequency \

a. 

$P(F_1) = \frac{416}{1000} = 0.416$

$P(B_1) = \frac{444}{1000} = 0.444$

b. 

$P(F_1 | B_1) = \frac{198}{444} = 0.4459459$

c. 

$P(B_1 | F_1) = \frac{198}{416} = 0.4759615$

d.

If $F_1$ and $B_1$ are independent, then $P(B_1) \cdot P(F_1) = P(B_1 \cap F_1)$.

But, $0.416 * 0.444 = 0.184704 \neq P(B_1 \cap F_1) = 0.198$




### Problem 6

a.

$P(H) = 0.3768983$

b.

$P(H | M) = 0.3348943$


$P(H | F) = 0.5111004$

c.

This movie appeals more to the female audience, with 51% of females giving it a high rating vs 33% of males. \

d.

$P(H) = 0.6578184$


$P(H | F) = 0.5339957$


$P(H | M) = 0.6744254$

This movie appeals more to the male audience, with 67% of men giving it a high rating vs only 53% of women. \




### Problem 8

Frequency

a.

$P(A) = \frac{306}{1000} = 0.306$

b.

$P(A | B) = \frac{56}{499} = 0.1122244$

Since $P(A | B) = 0.112 \neq P(A) = 0.306$, events $A$ and $B$ are not independent. \


Classical

a.
To have at least 5 children, the first 4 births must contain exactly 1 boy. \
$P(A) = \binom{4}{1} \cdot (0.5)^4 = 0.25$

b.
Given $B$, we need at least 4 more children, meaning exactly 0 boys in the next 3 births. \
$P(A | B) = (0.5)^3 = 0.125$

Since $P(A | B) = 0.125 \neq P(A) = 0.25$, events $A$ and $B$ are not independent. \


c.

Frequency

$P(A) = \frac{112}{1000} = 0.112$

$P(A | B) = \frac{62}{538} = 0.115$

Since $P(A | B) = 0.115 \approx P(A) = 0.112$, events $A$ and $B$ are approximately independent. \

Classical

$P(A) = 2 \cdot (0.5)^4 = 0.125$

$P(A | B) = P(\text{first 4 are all male}) = (0.5)^3 = 0.125$

Since $P(A | B) = 0.125 = P(A) = 0.125$, events $A$ and $B$ are independent. \




### Problem 12

a.

The probability that a woman is in favor of the levy is $0.4$. \

b.

Given a person is in favor of the levy, the probability that they are female is $\frac{8}{13} = 0.6153846$. \


### Problem 14

A - On steroids
B - Not on steroids


a.

$P(A \cap -) = 0.1 \cdot 0.2 = 0.02$

b.

$P(+) = P(+ | A) \cdot P(A) + P(+ | B) \cdot P(B) = 0.9 \cdot 0.2 + 0.1 * 0.8 = 0.26$


c.

$P(A | +) = \frac{0.9 \cdot 0.2}{0.26} = 0.6923077$


### Problem 17

If the two are independent then $P(A) \cdot P(B) = P(A \cap B)$. \

$P(A) = 0.5$

$P(B) = \binom{3}{1} \cdot 0.5^3 = 0.375$

$P(A \cap B) = 0.5^3 = 0.125$

$P(A) \cdot P(B) = 0.1875 \neq P(A \cap B) = 0.5^3 = 0.125$

Therefore, A and B are not independent events.



### Problem 18

$P(\text{two headed}) = \frac{1}{65}$

$P(\text{6 heads}) = P(6 | two) \cdot P(two) + P(6 | one) \cdot P(one) = 1 \cdot \frac{1}{65} + \frac{1}{64} \cdot \frac{64}{65} = \frac{2}{65}$

Now, using Bayes Theorem: \

$P(two | 6 heads) = \frac{P(6 | two) \cdot P(two)}{P(six heads)} = 0.5$.

So the probability that it was the 2 headed coin is $0.5$.



### Problem 23

a.

$0.6^3 = 0.216$


b.

$P(3 games) = P(I in 3) + P(Y in 3) = 0.4^3 + 0.6^3 = 0.28$


c.

$P(YIYIY) = 0.6 \cdot 0.4 \cdot 0.6 \cdot 0.4 \cdot 0.6 = 0.03456$

$P(IYIYI) =  0.4 \cdot 0.6 \cdot 0.4 \cdot 0.6 \cdot 0.4 = 0.02304$


### Problem 28

F = fair
N = not fair
R_1 = rolling 1

a. 

$P(R_1) = P(R_1 | F) \cdot P(F) + P(R_1 | N) \cdot P(N) = \frac{1}{6} \cdot 0.90 + \frac{1}{3} \cdot 0.10 = 0.1833$

b.

We can find this using Bayes Theorem: \

$P(F | R_1) = \frac{P(R_1 | F) \cdot P(F)}{P(R_1)} = \frac{0.15}{0.1833} = 0.818$



### Problem 30

a.

$P(S) = 0.7$

$P(T) = 0.3$

$P(D | S) = 0.4$

$P(D | T) = 0.8$


b.

$P(D) = P(D | S) \cdot P(S) + P(D | T) \cdot P(T) = 0.40 \cdot 0.70 + 0.80 \cdot 0.30 = 0.52$

c.

$P(S | D) = \frac{P(D | S) \cdot P(S)}{P(D)} = \frac{0.40 \cdot 0.70}{0.52} = 0.538$






### Optional Extra Credit King's Gold and Silver Chest Problem


Strategy #1: \

$P(\text{Free}) = \theta_g \cdot \theta_s + (1-\theta_g)(1-\theta_s) + \frac{1}{2}[\theta_g(1-\theta_s) + (1-\theta_g)\theta_s]$

$P_1 = 1 - \frac{1}{2}(\theta_g + \theta_s) + \theta_g\theta_s$


Strategy #2: \

$P(\text{Free} | G) = \theta_g^2 + \frac{1}{2} \cdot 2\theta_g(1-\theta_g) = \theta_g$

$P(\text{Free} | S) = \theta_s^2 + \frac{1}{2} \cdot 2\theta_s(1-\theta_s) = \theta_s$

$P_2 = \frac{\theta_g + \theta_s}{2}$

$P_1 - P_2 = (1-\theta_g)(1-\theta_s) > 0$

Strategy #1 is better.

lobster_data <- c(78, 66, 65, 63, 60, 60, 58, 56, 52, 50)
n <- length(lobster_data)
var(lobster_data)


